<a href="https://colab.research.google.com/github/TetianaMar-888/Python_for_ds_tasks/blob/main/SQL_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Some tasks from SQL

In [2]:
import pandas as pd

In [3]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.4.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (7.5 kB)
Downloading mysql_connector_python-9.4.0-cp312-cp312-manylinux_2_28_x86_64.whl (33.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.9/33.9 MB 21.0 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.4.0

In [4]:
import mysql.connector
from mysql.connector.connection import MySQLConnection
import datetime

In [5]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.43)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=6459fe7f67f175b7b1e6f56fd70cfdaa557c7658f8029658181ef1d5a3d4aaa1
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [6]:
from pandasql import sqldf

In [7]:
pysqldf = lambda q: sqldf(q, globals())

In [8]:
con = mysql.connector.connect(user='student', password='IAmLearningSQL',
                              host='shinkansen.proxy.rlwy.net',
                              database='employees',
                              port= 50507)

In [9]:
cursor = con.cursor()

In [10]:
import warnings
warnings.filterwarnings('ignore')

#1. Joining the "employees" and "salaries" tables

Output a list of 10 employees, their emp_no, first_name, last_name and their current salary. In this case, the order of the employees does not matter, the point is to get the table structure correct.

З'єднання таблиць "employees" та "salaries"
Виведіть список з 10 співробітників, їх emp_no, first_name, last_name та їхню поточну зарплату. В даному випадку порядок співробіників не має значення, суть в тому аби отримати правильну структуру таблиці.

In [10]:
df = pd.read_sql(f'select * from employees',  con)

In [11]:
df.head()

   emp_no  birth_date first_name last_name gender   hire_date
0   10001  1953-09-02     Georgi   Facello      M  1986-06-26
1   10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
2   10003  1959-12-03      Parto   Bamford      M  1986-08-28
3   10004  1954-05-01  Chirstian   Koblick      M  1986-12-01
4   10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12

In [12]:
df_salary =pd.read_sql_query("SELECT e.emp_no, e.first_name, e.last_name, s.salary, s.to_date FROM employees e JOIN salaries s ON e.emp_no = s.emp_no ORDER BY e.emp_no LIMIT 20", con)

In [13]:
df_salary.head(10)

   emp_no first_name last_name  salary     to_date
0   10001     Georgi   Facello   60117  1987-06-26
1   10001     Georgi   Facello   62102  1988-06-25
2   10001     Georgi   Facello   66074  1989-06-25
3   10001     Georgi   Facello   66596  1990-06-25
4   10001     Georgi   Facello   66961  1991-06-25
5   10001     Georgi   Facello   71046  1992-06-24
6   10001     Georgi   Facello   74333  1993-06-24
7   10001     Georgi   Facello   75286  1994-06-24
8   10001     Georgi   Facello   75994  1995-06-24
9   10001     Georgi   Facello   76884  1996-06-23

Since an employee may work in the company for a long time or even in different positions, we need to select only the current salary that the employee receive right now.

In [15]:
df_salary =pd.read_sql_query("SELECT e.emp_no, e.first_name, e.last_name, s.salary FROM employees e JOIN salaries s ON e.emp_no = s.emp_no WHERE s.to_date = '9999-01-01' ORDER BY e.emp_no LIMIT 10", con)

In [16]:
df_salary.head(10)

   emp_no first_name  last_name  salary
0   10001     Georgi    Facello   88958
1   10002    Bezalel     Simmel   72527
2   10003      Parto    Bamford   43311
3   10004  Chirstian    Koblick   74057
4   10005    Kyoichi   Maliniak   94692
5   10006     Anneke    Preusig   59755
6   10007    Tzvetan  Zielinski   88070
7   10009     Sumant       Peac   94409
8   10010  Duangkaew   Piveteau   80324
9   10012   Patricio  Bridgland   54423

Now we see a table with employee numbers, first name, last name, and their current salary.

#2. Joining the "employees" and "titles" tables

Output a list of 10 employees, their `emp_no`, `first_name`, `last_name`, and their **current** **job** **title**. In this case, the order of the employees doesn't matter, the point is to get the table structure right.



З'єднання таблиць "employees" та "titles"

  Виведіть список з 10 співробітників, їх `emp_no`, `first_name`, `last_name` та їхню **поточну** **посаду**. В даному випадку порядок співробіників не має значення, суть в тому аби отримати правильну структуру таблиці.

In [17]:
df_title =pd.read_sql_query("SELECT e.emp_no, e.first_name, e.last_name, t.title FROM employees e JOIN titles t ON e.emp_no = t.emp_no WHERE t.to_date = '9999-01-01' ORDER BY e.emp_no LIMIT 10", con)

In [18]:
df_title.head(10)

   emp_no first_name  last_name            title
0   10001     Georgi    Facello  Senior Engineer
1   10002    Bezalel     Simmel            Staff
2   10003      Parto    Bamford  Senior Engineer
3   10004  Chirstian    Koblick  Senior Engineer
4   10005    Kyoichi   Maliniak     Senior Staff
5   10006     Anneke    Preusig  Senior Engineer
6   10007    Tzvetan  Zielinski     Senior Staff
7   10009     Sumant       Peac  Senior Engineer
8   10010  Duangkaew   Piveteau         Engineer
9   10012   Patricio  Bridgland  Senior Engineer

In [19]:
pd.read_sql_query("SELECT emp_no, COUNT(*) AS active_positions FROM titles WHERE to_date = '9999-01-01' GROUP BY emp_no HAVING active_positions >= 1 ORDER BY active_positions DESC", con)

        emp_no  active_positions
0       491836                 1
1       491838                 1
2       491839                 1
3       491840                 1
4       491841                 1
...        ...               ...
240119  410075                 1
240120  410076                 1
240121  410077                 1
240122  410078                 1
240123  410079                 1

[240124 rows x 2 columns]

In [20]:
df_title.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_no      10 non-null     int64
 1   first_name  10 non-null     object
 2   last_name   10 non-null     object
 3   title       10 non-null     object
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes

We created a table with the employees’ data and their current positions. We also checked whether any employees are working in multiple positions to ensure that our table is error-free.

Ми створили таблицю з даними співробітника і зайнятої поточної позиції. Добатково перевірили чи не працює наш співробітник одночасно паралельно на декілької позиціях, щоб впевнитись: що наша таблиця без похибок.

#3. Joining the tables "employees", "dept_emp" and "departments"

Output a list of 10 employees, their emp_no, first_name, last_name and the department they currently work in. In this case, the order of the employees does not matter, the point is to get the table structure correct.


З'єднання таблиць "employees", "dept_emp" та "departments"
Виведіть список з 10 співробітників, їх emp_no, first_name, last_name та відділ, де вони зараз працюють. В даному випадку порядок співробіників не має значення, суть в тому аби отримати правильну структуру таблиці.

In [21]:
df_depart = pd.read_sql_query("SELECT e.emp_no, e.first_name, e.last_name, dn.dept_name FROM employees e JOIN dept_emp dno ON e.emp_no = dno.emp_no JOIN departments dn ON dno.dept_no = dn.dept_no WHERE dno.to_date = '9999-01-01'", con)

In [22]:
df_depart.head(10)

   emp_no first_name    last_name         dept_name
0   10038       Huan        Lortz  Customer Service
1   10049      Basil       Tramer  Customer Service
2   10060   Breannda  Billingsley  Customer Service
3   10088   Jungsoon     Syrzycki  Customer Service
4   10112   Yuichiro        Swick  Customer Service
5   10126     Kayoko     Valtorta  Customer Service
6   10128    Babette        Lamba  Customer Service
7   10137      Maren       Hutton  Customer Service
8   10154    Abdulah    Thibadeau  Customer Service
9   10164     Jagoda    Braunmuhl  Customer Service

In [23]:
df_depart.dept_name.unique()

array(['Customer Service', 'Development', 'Finance', 'Human Resources',
       'Marketing', 'Production', 'Quality Management', 'Research',
       'Sales'], dtype=object)

In [24]:
df_depart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240124 entries, 0 to 240123
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   emp_no      240124 non-null  int64
 1   first_name  240124 non-null  object
 2   last_name   240124 non-null  object
 3   dept_name   240124 non-null  object
dtypes: int64(1), object(3)
memory usage: 7.3+ MB

In this task, we joined data from three tables to form a table with employees and the name of the current department they work in.

У цій задачі ми об'єднали дані з трьох таблиць, щоб сформувати таблицю зі співробітниками та назвою відділу, в якому вони зараз працюють.

#4. Your company's management wants to gain a clear understanding of the distribution of employees across different departments. Specifically, you need to:
- Determine the number of unique employees in each department.
- Present this information in an orderly manner, starting with the department with the largest number of employees.

For this task, you need tables
- `departments`, which contains information about departments (including `dept_name` and `dept_no`),
- and `dept_emp`, which contains information about employees belonging to departments (including `emp_no` and `dept_no`).

Керівництво вашої компанії прагне отримати чітке розуміння щодо розподілу працівників між різними відділами. Специфічно, потрібно:
  - Визначити кількість унікальних працівників у кожному відділі.
  - Представити цю інформацію у впорядкованому вигляді, починаючи з відділу з найбільшою кількістю працівників.
    
  Для цієї задачі вам потрібні таблиці
    - `departments`, яка містить інформацію про відділи (включаючи `dept_name` та `dept_no`),
    - і `dept_emp`, яка містить відомості про приналежність працівників до відділів (включаючи `emp_no` та `dept_no`).

In [25]:
df_depart_emp = pd.read_sql_query("SELECT dn.dept_name, COUNT(DISTINCT dno.emp_no) AS employee_count FROM dept_emp dno JOIN departments dn ON dno.dept_no = dn.dept_no WHERE dno.to_date = '9999-01-01' GROUP BY dn.dept_name ORDER BY employee_count DESC", con)
df_depart_emp

            dept_name  employee_count
0         Development           61386
1          Production           53304
2               Sales           37701
3    Customer Service           17569
4            Research           15441
5           Marketing           14842
6  Quality Management           14546
7     Human Resources           12898
8             Finance           12437

We selected employees currently working in the company and sorted them by number in each department in descending order.

#5. Find out who the highest paid employee in the Development department is.
You need to determine the employee's ID number, first name, last name, and salary.


Знайдіть, хто є найбільш високооплачуваним працівником у відділі Development. Вам потрібно визначити ідентифікаційний номер, ім'я, прізвище та зарплату цього працівника.

In [26]:
df_dev = pd.read_sql_query("SELECT e.emp_no, e.first_name, e.last_name, s.salary FROM employees e JOIN salaries s ON e.emp_no = s.emp_no JOIN dept_emp dno ON e.emp_no = dno.emp_no JOIN departments dn ON dno.dept_no = dn.dept_no WHERE dn.dept_name = 'Development' AND s.to_date = '9999-01-01' ORDER BY s.salary DESC LIMIT 1", con)
df_dev

   emp_no first_name last_name  salary
0   13386    Khosrow    Sgarro  144434

As a result, we received information about the highest paid employee in the Development department. To check the information, you can remove the limit and we will see all employees of this department.

#6. We want to determine which department the highest paid employee in the company works in.
Output his/her identification number, first name, last name, salary, and department.


*Ми хочемо визначити, в якому відділі працює найбільш високооплачуваний співробітник в компанії. Виведіть його ідентифікаційний номер, ім'я, прізвище, зарплату та відділ.

In [27]:
df_highest = pd.read_sql_query("SELECT e.emp_no, e.first_name, e.last_name, s.salary, dn.dept_name FROM employees e JOIN salaries s ON e.emp_no = s.emp_no JOIN dept_emp dno ON e.emp_no = dno.emp_no JOIN departments dn ON dno.dept_no = dn.dept_no WHERE s.to_date = '9999-01-01' ORDER BY s.salary DESC LIMIT 1", con)
df_highest

   emp_no first_name last_name  salary dept_name
0   43624   Tokuyasu     Pesch  158220     Sales

We see that currently, the highest-paid employee is from the Sales department.

#7. Display the number, first name, last name, and salary of the employee with the third highest salary
(i.e., if we were to sort employees by decreasing salary, this one would be third in the list). Only one row of data needs to be displayed.

*Виведіть номер, імʼя, прізвище і розмір зарплати співробітника з третьою найвищою зарплатою (тобто якщо б ми відсотували співробітників за спаданням ЗП, цей був би третім в списку). Треба вивести лише один рядок даних.

In [28]:
df_highest_third = pd.read_sql_query("SELECT e.emp_no, e.first_name, e.last_name, s.salary FROM employees e JOIN salaries s ON e.emp_no = s.emp_no WHERE s.to_date = '9999-01-01' ORDER BY s.salary DESC LIMIT 1 OFFSET 2", con)
df_highest_third

   emp_no first_name last_name  salary
0   47978     Xiahua  Whitcomb  155709

That is, the query will give us the third highest-paid employee, because at the end we added the condition "OFFSET 2". This means that we previously sorted the current salary in descending order and now we want to see information about the third highest-paid employee in the company.

*Тобто, запит видасть нам третього найвисокооплачуванішого працівника, оскільки в кінці ми додали умову "OFFSET 2". Це означає, що раніше ми відсортували поточну зарплату в порядку спадання, а тепер хочемо побачити інформацію про третього найвисокооплачуванішого працівника в компанії.

#8. Find employees with multiple positions
Some employees may change positions during their time with the company. Identify all employees who have held more than one position during their time with the company. Display their `emp_no`, `first_name`, `last_name` and a list of all positions they have held.

  Знайдіть співробітників з декількома посадами
  
  Деякі співробітники можуть змінювати свої посади протягом роботи в компанії. Визначте всіх співробітників, які мали більше однієї посади за час роботи в компанії. Відобразіть їх `emp_no`, `first_name`, `last_name` та список всіх посад, на яких вони працювали.

In [29]:
df_multiple = pd.read_sql_query("SELECT e.emp_no, e.first_name, e.last_name, GROUP_CONCAT(' ', t.title) AS positions FROM employees e JOIN titles t ON e.emp_no = t.emp_no GROUP BY e.emp_no HAVING COUNT(t.title) > 1", con)
df_multiple

,emp_no,first_name,last_name,positions
0,10004,Chirstian,Koblick,"Engineer, Senior Engineer"
1,10005,Kyoichi,Maliniak,"Senior Staff, Staff"
2,10007,Tzvetan,Zielinski,"Senior Staff, Staff"
3,10009,Sumant,Peac,"Assistant Engineer, Engineer, Senior Engineer"
4,10012,Patricio,Bridgland,"Engineer, Senior Engineer"
...,...,...,...,...
140265,499988,Bangqing,Kleiser,"Senior Staff, Staff"
140266,499992,Siamak,Salverda,"Senior Staff, Staff"
140267,499996,Zito,Baaz,"Engineer, Senior Engineer"
140268,499997,Berhard,Lenart,"Engineer, Senior Engineer"
140269,499998,Patricia,Breugel,"Senior Staff, Staff"

We grouped all employee positions in the company into one column "positions" and separated them by a comma with a space for better perception of information.

#9. Transfers Between Departments

Employees sometimes move between departments. Identify all employees who have worked in more than one department. Display their `emp_no`, `first_name`, `last_name`, and the names of all departments they have worked in.

*Переводи між відділами

Співробітники іноді переходять між відділами. Визначте всіх співробітників, які працювали в більш ніж одному відділі. Відобразіть їх `emp_no`, `first_name`, `last_name` та назви всіх відділів, в яких вони працювали.

In [30]:
df_transfer = pd.read_sql_query("SELECT e.emp_no, e.first_name, e.last_name, GROUP_CONCAT(' ', dn.dept_name) AS departments FROM employees e JOIN dept_emp dno ON e.emp_no = dno.emp_no JOIN departments dn ON dno.dept_no = dn.dept_no GROUP BY e.emp_no HAVING COUNT(dn.dept_name) > 1", con)
df_transfer

       emp_no    first_name last_name                      departments
0       10010     Duangkaew  Piveteau   Quality Management, Production
1       10018      Kazuhide      Peha          Development, Production
2       10029         Otmar    Herbst   Production, Quality Management
3       10040         Weiyi   Meriste            Development, Research
4       10050       Yinghua    Dredge                   Sales, Finance
...       ...           ...       ...                              ...
31574  499955  Kankanahalli    Zucker    Development, Customer Service
31575  499964         Randy    Matzov   Quality Management, Production
31576  499975        Masali   Chorvat         Human Resources, Finance
31577  499983           Uri    Juneja     Customer Service, Production
31578  499992        Siamak  Salverda       Human Resources, Marketing

[31579 rows x 4 columns]

In this table, we displayed all employees who worked in two or more departments.

*В цій таблиці ми відобразили всіх працівників, які працювали в двох і більше відділах.

In [31]:
df_transfer_now = pd.read_sql_query("SELECT e.emp_no, e.first_name, e.last_name, GROUP_CONCAT(' ', dn.dept_name ORDER BY dno.from_date) AS departments FROM employees e JOIN dept_emp dno ON e.emp_no = dno.emp_no JOIN departments dn ON dno.dept_no = dn.dept_no WHERE e.emp_no IN (SELECT emp_no FROM dept_emp WHERE to_date = '9999-01-01') GROUP BY e.emp_no HAVING COUNT(dn.dept_name) > 1 ORDER BY e.emp_no", con)
df_transfer_now

       emp_no    first_name last_name                      departments
0       10010     Duangkaew  Piveteau   Production, Quality Management
1       10018      Kazuhide      Peha          Development, Production
2       10029         Otmar    Herbst   Production, Quality Management
3       10040         Weiyi   Meriste            Development, Research
4       10050       Yinghua    Dredge                   Finance, Sales
...       ...           ...       ...                              ...
25203  499938       JiYoung   Binding    Customer Service, Development
25204  499955  Kankanahalli    Zucker    Customer Service, Development
25205  499964         Randy    Matzov   Quality Management, Production
25206  499983           Uri    Juneja     Customer Service, Production
25207  499992        Siamak  Salverda       Human Resources, Marketing

[25208 rows x 4 columns]

As we can see from the query, in this table we have only kept employees who worked in two or more departments and are currently employed by the company. We have also displayed their departments where they worked in chronological order.

*Як ми бачимо з запиту, в цій таблиці ми лишили лише працівників, які працювали в двох і більше відділах і працюють в компанії станом на зараз. Також відобразили їхні відділи де вони працювали в хронологічному порядку.

#10. Current Manager Salary
For each department, enter the department name, the current manager's `emp_no`, their `first_name`, `last_name`, and current salary. Make sure you are getting the **current** salary of the **current** manager.

**Поточна зарплата керівника**   
Для кожного відділу вкажіть назву відділу, `emp_no` поточного керівника, його `first_name`, `last_name` та поточну зарплату. Переконайтеся, що ви отримуєте саме **поточну** зарплату **поточного** керівника.

In [32]:
df_manger = pd.read_sql_query("SELECT dn.dept_name, e.emp_no, e.first_name, e.last_name, s.salary FROM employees e JOIN dept_manager dm ON e.emp_no = dm.emp_no JOIN departments dn ON dm.dept_no = dn.dept_no JOIN salaries s ON e.emp_no = s.emp_no WHERE dm.to_date = '9999-01-01' AND s.to_date = '9999-01-01' ORDER BY s.salary DESC, dn.dept_name", con)
df_manger

            dept_name  emp_no first_name   last_name  salary
0           Marketing  110039   Vishwani    Minakawa  106491
1               Sales  111133      Hauke       Zhang  101987
2             Finance  110114      Isamu  Legleitner   83457
3            Research  111534     Hilary      Kambil   79393
4         Development  110567       Leon    DasSarma   74510
5  Quality Management  110854       Dung       Pesch   72876
6     Human Resources  110228    Karsten     Sigstam   65400
7    Customer Service  111939    Yuchang     Weedman   58745
8          Production  110420      Oscar    Ghazalie   56654

Since we specified the current date "to_date = '9999-01-01'" in the "dept_manager" table and in the "salaries" table, we got exactly the current salary of the current manager of all departments in the company.

*Оскільки ми вказали дату станом на зараз to_date = '9999-01-01' в таблиці менеджерів та в таблиці заробітньої платні, ми отримали саме поточну зарплату поточного керівника всих відділів в компанії.

#Using Window Functions

#1. Using ROW_NUMBER
For the first 10 employees (by emp_no), output their emp_no, first_name, last_name, and the employee's serial number in the table.

**Використання ROW_NUMBER**
Для перших 10 співробітників (за emp_no) виведіть їх emp_no, first_name, last_name, а також порядковий номер співробітника в таблиці.

In [37]:
df_row = pd.read_sql_query("SELECT emp_no, first_name, last_name, ROW_NUMBER() OVER (ORDER BY emp_no) AS serial_number FROM employees LIMIT 10", con)
df_row

   emp_no first_name  last_name  serial_number
0   10001     Georgi    Facello              1
1   10002    Bezalel     Simmel              2
2   10003      Parto    Bamford              3
3   10004  Chirstian    Koblick              4
4   10005    Kyoichi   Maliniak              5
5   10006     Anneke    Preusig              6
6   10007    Tzvetan  Zielinski              7
7   10008     Saniya   Kalloufi              8
8   10009     Sumant       Peac              9
9   10010  Duangkaew   Piveteau             10

#2. Output salary dynamics for an employee
Output `emp_no`, start date (`from_date`), salary, and previous salary value for the employee with `emp_no = 10001`.

*Вивести зарплатну динаміку співробітника
Виведіть `emp_no`, дату початку (`from_date`), зарплату та попереднє значення зарплати для співробітника з `emp_no = 10001`.

In [10]:
df_dynamic = pd.read_sql_query("SELECT emp_no, from_date, salary, LAG(salary) OVER (ORDER BY from_date) AS previous_salary FROM salaries WHERE emp_no = 10001", con)
df_dynamic

    emp_no   from_date  salary  previous_salary
0    10001  1986-06-26   60117              NaN
1    10001  1987-06-26   62102          60117.0
2    10001  1988-06-25   66074          62102.0
3    10001  1989-06-25   66596          66074.0
4    10001  1990-06-25   66961          66596.0
5    10001  1991-06-25   71046          66961.0
6    10001  1992-06-24   74333          71046.0
7    10001  1993-06-24   75286          74333.0
8    10001  1994-06-24   75994          75286.0
9    10001  1995-06-24   76884          75994.0
10   10001  1996-06-23   80013          76884.0
11   10001  1997-06-23   81025          80013.0
12   10001  1998-06-23   81097          81025.0
13   10001  1999-06-23   84917          81097.0
14   10001  2000-06-22   85112          84917.0
15   10001  2001-06-22   85097          85112.0
16   10001  2002-06-22   88958          85097.0

Using the LAG function, we got the following dynamic table with a column of previous salary for dynamics and comparison.

*З допомогою функції LAG ми отримали таку динамічну таблицю з стовпцем попередньої зарплати для динаміки та порівняння.

#3. Determining salary rank within a department
Return emp_no, dept_name, current salary, and employee rank within their department by salary.

*Визначення рангу зарплати в межах відділу

Виведіть emp_no, dept_name, поточну зарплату та ранг співробітника в межах його відділу за розміром зарплати.

In [19]:
df_rank = pd.read_sql_query("SELECT e.emp_no, dn.dept_name, s.salary, RANK() OVER (PARTITION BY dn.dept_name ORDER BY s.salary DESC) AS salary_rank FROM employees e JOIN dept_emp dno ON e.emp_no = dno.emp_no JOIN departments dn ON dno.dept_no = dn.dept_no JOIN salaries s ON e.emp_no = s.emp_no WHERE dno.to_date = '9999-01-01' AND s.to_date = '9999-01-01'", con)
df_rank

        emp_no         dept_name  salary  salary_rank
0        18006  Customer Service  144866            1
1        96957  Customer Service  143950            2
2       432583  Customer Service  143937            3
3        98169  Customer Service  143832            4
4       485205  Customer Service  141555            5
...        ...               ...     ...          ...
240119  219496             Sales   40946        37697
240120   63446             Sales   40811        37698
240121  213121             Sales   40652        37699
240122  222098             Sales   40392        37700
240123  411947             Sales   39426        37701

[240124 rows x 4 columns]

Thus, we derived ranks for employees based on their current salary.

*Таким чином ми вивели ранги для співробітників в залежності від їхньої поточної зарплати.

#4. Finding the change in an employee's salary over the last 2 years
Return the difference between the current salary of the employee with emp_no = 10001 and his salary 2 years ago. Response format: employee number, salary_2_years_ago, current salary, difference in salaries 2 years ago and now.

*Знаходження зміни зарплати співробітника протягом останніх 2 років

Виведіть різницю між поточною зарплатою співробітника з emp_no = 10001 та його зарплатою 2 роки тому. Формат відповіді: номер співробітника, salary_2_years_ago, поточна ЗП, різниця у зарплатах 2 роки тому і зараз.

In [23]:
df_diff = pd.read_sql_query("""
WITH current_salary AS (
    SELECT
        emp_no,
        salary,
        from_date
    FROM salaries
    WHERE to_date = '9999-01-01' AND emp_no = 10001
),
salary_2_years_ago AS (
    SELECT
        s.emp_no,
        s.salary,
        s.from_date,
        ROW_NUMBER() OVER (PARTITION BY s.emp_no ORDER BY s.from_date DESC) AS rn
    FROM salaries s
    JOIN current_salary c ON s.emp_no = c.emp_no
    WHERE s.from_date <= DATE_SUB(c.from_date, INTERVAL 2 YEAR)
)
SELECT
    c.emp_no,
    s.salary AS salary_2_years_ago,
    c.salary AS current_salary,
    c.salary - s.salary AS difference
FROM current_salary c
JOIN salary_2_years_ago s
    ON c.emp_no = s.emp_no AND s.rn = 1
WHERE c.emp_no = 10001;
""", con)

df_diff

   emp_no  salary_2_years_ago  current_salary  difference
0   10001               85112           88958        3846

#5. Determining the highest salary increase
Find the employee who received the highest salary increase during the year ending 1 year before the most recent date in the database (maximum value of from_date in the salaries table). Response format: employee number, salary from the previous year, salary grade, and amount of salary change.

*Визначення найвищого зростання зарплати
Знайдіть співробітника, який отримав найбільше збільшення зарплати протягом року, який закінчився 1 рік до найновішої дати в базі даних (максимальне значення from_date в таблиці salaries). Формат відповіді: номер співробітника, ЗП з попереднього року, поточка ЗП, на яку суму змінилась ЗП.

In [17]:
df_highest_salary = pd.read_sql_query("""
WITH max_date AS (
    SELECT MAX(from_date) AS max_date
    FROM salaries
),
prev_year_date AS (
    SELECT DATE_SUB(max_date, INTERVAL 1 YEAR) AS target_date
    FROM max_date
),
filtered AS (
    SELECT s.*
    FROM salaries s
    JOIN prev_year_date p
      ON s.from_date >= p.target_date AND s.from_date <= (SELECT max_date FROM max_date)
),
with_lead AS (
    SELECT
        f.emp_no,
        f.salary,
        LEAD(f.salary) OVER (PARTITION BY f.emp_no ORDER BY f.from_date) AS next_salary
    FROM filtered f
)
SELECT
    emp_no,
    salary AS salary_from_previous_year,
    next_salary AS current_salary,
    next_salary - salary AS salary_change
FROM with_lead
WHERE next_salary IS NOT NULL
ORDER BY salary_change DESC
LIMIT 1;
""", con)

df_highest_salary

   emp_no  salary_from_previous_year  current_salary  salary_change
0  240126                      54522           59021           4499

#6. Average salary and first employee in each position
For each position, output its name, the average salary of employees in it, the name of the first employee (or employees, if several people were hired for this position on the same day) who was hired for this position (according to the hire_date), and the hire_date of this employee or employees.In the response, sort the results by job title and employee name.

*Середня зарплата та перший праціник на кожній посаді

Для кожної посади виведіть її назву, середню зарплату співробітників на ній, ім'я першого співробітника (або співробітників, якщо в один і той самий день було прийнято на цю посаду кілька людей), який був прийнятий на цю посаду (згідно дати прийому на роботу - hire_date), а також hire_date цього співробітника чи співробітників. У відповіді відсортуйте результати за назвою посади і імʼям співробітника.

In [11]:
df_avg = pd.read_sql_query("""
WITH avg_salary AS (
    SELECT
        t.title,
        ROUND(AVG(s.salary), 2) AS avg_salary
    FROM titles t
    JOIN salaries s ON t.emp_no = s.emp_no
    GROUP BY t.title
),
first_hire_date AS (
    SELECT
        t.title,
        MIN(e.hire_date) AS min_hire_date
    FROM titles t
    JOIN employees e ON t.emp_no = e.emp_no
    GROUP BY t.title
),
first_employee AS (
    SELECT
        t.title,
        e.first_name,
        e.last_name,
        e.hire_date
    FROM titles t
    JOIN employees e ON t.emp_no = e.emp_no
    JOIN first_hire_date fh
      ON fh.title = t.title AND fh.min_hire_date = e.hire_date
)
SELECT
    a.title,
    a.avg_salary,
    f.first_name,
    f.last_name,
    f.hire_date
FROM avg_salary a
JOIN first_employee f ON a.title = f.title
ORDER BY a.title, f.first_name, f.last_name;
""", con)

df_avg

                 title  avg_salary   first_name      last_name   hire_date
0   Assistant Engineer    59304.99        Taizo         Orsini  1985-02-01
1             Engineer    59508.04        Arvin       Birdsall  1985-02-01
2             Engineer    59508.04       Divier      Marrakchi  1985-02-01
3             Engineer    59508.04         Gian          Rothe  1985-02-01
4             Engineer    59508.04       Kannan         Mahnke  1985-02-01
5             Engineer    59508.04         Mona  Beutelspacher  1985-02-01
6             Engineer    59508.04       Poorav         Gecsei  1985-02-01
7             Engineer    59508.04        Taizo         Orsini  1985-02-01
8             Engineer    59508.04      Zdislav       Ferriere  1985-02-01
9              Manager    66924.27         Arie        Staelin  1985-01-01
10             Manager    66924.27     DeForest       Hagimont  1985-01-01
11             Manager    66924.27         Ebru          Alpin  1985-01-01
12             Manager    66924.27    Krassimir        Wegerle  1985-01-01
13             Manager    66924.27    Margareta     Markovitch  1985-01-01
14             Manager    66924.27    Peternela        Onuegbe  1985-01-01
15             Manager    66924.27  Przemyslawa      Kaelbling  1985-01-01
16             Manager    66924.27      Shirish   Ossenbruggen  1985-01-01
17             Manager    66924.27        Tonny    Butterworth  1985-01-01
18     Senior Engineer    60543.22        Arvin       Birdsall  1985-02-01
19     Senior Engineer    60543.22       Divier      Marrakchi  1985-02-01
20     Senior Engineer    60543.22         Gian          Rothe  1985-02-01
21     Senior Engineer    60543.22       Jayesh       Minakawa  1985-02-01
22     Senior Engineer    60543.22       Kannan         Mahnke  1985-02-01
23     Senior Engineer    60543.22         Mona  Beutelspacher  1985-02-01
24     Senior Engineer    60543.22       Poorav         Gecsei  1985-02-01
25     Senior Engineer    60543.22      Zdislav       Ferriere  1985-02-01
26        Senior Staff    70470.84         Ebru          Alpin  1985-01-01
27        Senior Staff    70470.84    Margareta     Markovitch  1985-01-01
28               Staff    69309.10         Arie        Staelin  1985-01-01
29               Staff    69309.10  Przemyslawa      Kaelbling  1985-01-01
30               Staff    69309.10      Shirish   Ossenbruggen  1985-01-01
31               Staff    69309.10        Tonny    Butterworth  1985-01-01
32    Technique Leader    59294.37     DeForest       Hagimont  1985-01-01
33    Technique Leader    59294.37    Krassimir        Wegerle  1985-01-01
34    Technique Leader    59294.37    Peternela        Onuegbe  1985-01-01

#7. Using NTILE

Divide the specified employees into 3 groups according to their current salary. Print `emp_no`, `first_name`, `last_name`, salary and group number for each of them.

`emp_no` of employees whose salaries we will investigate: `419748, 496734, 264134, 209076, 86631, 456171, 16887, 230255, 246465, 420097, 44362, 280370, 479975, 433320, 473949`



*Використання NTILE

Розподіліть зазначених співробітників на 3 групи за розміром їх поточної зарплати. Виведіть `emp_no`, `first_name`, `last_name`, зарплату та номер групи для кожного з них.
`emp_no` співробітників, зарплати яких будемо досліджувати: `419748, 496734, 264134, 209076, 86631, 456171, 16887, 230255, 246465, 420097, 44362, 280370, 479975, 433320, 473949`

In [13]:
df_ntile = pd.read_sql_query("""
WITH salary_groups AS (
    SELECT
        e.emp_no,
        e.first_name,
        e.last_name,
        s.salary,
        NTILE(3) OVER (ORDER BY s.salary DESC) AS salary_group
    FROM employees e
    JOIN salaries s ON e.emp_no = s.emp_no
    WHERE e.emp_no IN (419748, 496734, 264134, 209076, 86631, 456171, 16887, 230255, 246465, 420097, 44362, 280370, 479975, 433320, 473949) AND s.to_date = '9999-01-01'
)
SELECT
    emp_no,
    first_name,
    last_name,
    salary,
    salary_group
FROM salary_groups
ORDER BY salary_group, emp_no;
""", con)

df_ntile

    emp_no first_name last_name  salary  salary_group
0    86631    Tristan     Isaac  133038             1
1   209076       Moon     Uhrik  133712             1
2   264134     Reuven    Uludag  134570             1
3   419748    Jixiang   Rindone  140784             1
4   496734   Dayanand    Morrey  136130             1
5    16887   Bernardo  Sinitsyn  129036             2
6   230255      Ennio     Lorcy  128018             2
7   246465    Apostol    Leuchs  127924             2
8   420097      Aimee   Stifter  126885             2
9   456171     Xuejun  Papsdorf  130010             2
10   44362     Manton     Kitai  126640             3
11  280370     Mayuko     Vesel  126629             3
12  433320    Gunilla  Takkinen  125600             3
13  473949    Pantung     Picht  124950             3
14  479975   Kazuhiro      Pews  126163             3

In [14]:
#con.close()