<a href="https://colab.research.google.com/github/TetianaMar-888/Python_for_ds_tasks/blob/main/Test_22_10_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.max.rows',130)
pd.set_option('display.max.columns',130)
pd.set_option('float_format', '{:.2f}'.format)

In [2]:
URL = "https://people.sc.fsu.edu/~jburkardt/data/csv/cities.csv"
df = pd.read_csv(URL)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LatD      128 non-null    int64
 1    "LatM"   128 non-null    int64
 2    "LatS"   128 non-null    int64
 3    "NS"     128 non-null    object
 4    "LonD"   128 non-null    int64
 5    "LonM"   128 non-null    int64
 6    "LonS"   128 non-null    int64
 7    "EW"     128 non-null    object
 8    "City"   128 non-null    object
 9    "State"  128 non-null    object
dtypes: int64(6), object(4)
memory usage: 10.1+ KB

In [ ]:
df.head()

,LatD,"""LatM""","""LatS""","""NS""","""LonD""","""LonM""","""LonS""","""EW""","""City""","""State"""
0,41,5,59,"""N""",80,39,0,"""W""","""Youngstown""",OH
1,42,52,48,"""N""",97,23,23,"""W""","""Yankton""",SD
2,46,35,59,"""N""",120,30,36,"""W""","""Yakima""",WA
3,42,16,12,"""N""",71,48,0,"""W""","""Worcester""",MA
4,43,37,48,"""N""",89,46,11,"""W""","""Wisconsin Dells""",WI

In [ ]:
df.columns = df.columns.str.replace('"', '').str.strip()
df['City'] = df['City'].astype(str)

In [ ]:
df.shape

(128, 10)

In [ ]:
df['City'] = df['City'].str.replace('"', '').str.replace('"', '')

In [ ]:
df['City']

0               "Youngstown"
1                  "Yankton"
2                   "Yakima"
3                "Worcester"
4          "Wisconsin Dells"
5            "Winston-Salem"
6                 "Winnipeg"
7               "Winchester"
8               "Wilmington"
9               "Wilmington"
10               "Williston"
11            "Williamsport"
12              "Williamson"
13           "Wichita Falls"
14                 "Wichita"
15                "Wheeling"
16         "West Palm Beach"
17               "Wenatchee"
18                    "Weed"
19                "Waycross"
20                  "Wausau"
21                "Waukegan"
22               "Watertown"
23               "Watertown"
24                "Waterloo"
25               "Waterbury"
26              "Washington"
27                  "Warren"
28             "Walla Walla"
29                    "Waco"
30               "Vincennes"
31                "Victoria"
32               "Vicksburg"
33               "Vancouver"
34             "Valley City"
35                "Valdosta"
36                   "Utica"
37               "Uniontown"
38                   "Tyler"
39              "Twin Falls"
40              "Tuscaloosa"
41                  "Tupelo"
42                   "Tulsa"
43                  "Tucson"
44                "Trinidad"
45                 "Trenton"
46           "Traverse City"
47                 "Toronto"
48                  "Topeka"
49                  "Toledo"
50               "Texarkana"
51             "Terre Haute"
52                   "Tampa"
53             "Tallahassee"
54                  "Tacoma"
55                "Syracuse"
56              "Swainsboro"
57                  "Sumter"
58             "Stroudsburg"
59                "Stockton"
60           "Stevens Point"
61            "Steubenville"
62                "Sterling"
63                "Staunton"
64             "Springfield"
65             "Springfield"
66             "Springfield"
67             "Springfield"
68                 "Spokane"
69              "South Bend"
70             "Sioux Falls"
71              "Sioux City"
72              "Shreveport"
73                 "Sherman"
74                "Sheridan"
75                "Seminole"
76                   "Selma"
77                 "Sedalia"
78                 "Seattle"
79                "Scranton"
80             "Scottsbluff"
81             "Schenectady"
82                "Savannah"
83      "Sault Sainte Marie"
84                "Sarasota"
85              "Santa Rosa"
86                "Santa Fe"
87           "Santa Barbara"
88               "Santa Ana"
89                "San Jose"
90           "San Francisco"
91                "Sandusky"
92               "San Diego"
93          "San Bernardino"
94             "San Antonio"
95              "San Angelo"
96          "Salt Lake City"
97               "Salisbury"
98                 "Salinas"
99                  "Salina"
100                 "Salida"
101                  "Salem"
102             "Saint Paul"
103            "Saint Louis"
104           "Saint Joseph"
105           "Saint Joseph"
106        "Saint Johnsbury"
107            "Saint Cloud"
108        "Saint Augustine"
109                "Saginaw"
110             "Sacramento"
111                "Rutland"
112                "Roswell"
113            "Rocky Mount"
114           "Rock Springs"
115               "Rockford"
116              "Rochester"
117              "Rochester"
118                "Roanoke"
119               "Richmond"
120               "Richmond"
121              "Richfield"
122            "Rhinelander"
123                   "Reno"
124                 "Regina"
125              "Red Bluff"
126                "Reading"
127                "Ravenna"
Name: City, dtype: object

In [ ]:
help(str.lower)

Help on method_descriptor:

lower(self, /) unbound builtins.str method
    Return a copy of the string converted to lowercase.

In [ ]:
letters = set("".join(df['City'].str.lower()))
print(letters)

{'c', ' ', '"', 'p', 'g', 'o', 'b', 'f', 'j', 'v', 'a', 'n', '-', 'w', 'd', 't', 'l', 'i', 'm', 'e', 'h', 'u', 'r', 'y', 's', 'k', 'x'}

In [ ]:
#df

In [ ]:
sorted_letters = sorted(letters)
print(sorted_letters)

[' ', '"', '-', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y']

In [ ]:
sorted_letters[3:]

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y']

In [ ]:
df['letters'] = [sorted_letters] * len(df)

In [ ]:
df["hash32"] = df["letters"].apply(
    lambda s: hash(tuple(s)) % 2**32
)

In [ ]:
print(df["letters"])

0      [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
1      [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
2      [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
3      [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
4      [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
5      [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
6      [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
7      [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
8      [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
9      [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
10     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
11     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
12     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
13     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
14     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
15     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
16     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
17     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
18     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
19     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
20     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
21     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
22     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
23     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
24     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
25     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
26     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
27     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
28     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
29     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
30     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
31     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
32     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
33     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
34     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
35     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
36     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
37     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
38     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
39     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
40     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
41     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
42     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
43     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
44     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
45     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
46     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
47     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
48     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
49     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
50     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
51     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
52     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
53     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
54     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
55     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
56     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
57     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
58     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
59     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
60     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
61     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
62     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
63     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
64     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
65     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
66     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
67     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
68     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
69     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
70     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
71     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
72     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
73     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
74     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
75     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
76     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
77     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
78     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
79     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
80     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
81     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
82     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
83     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
84     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
85     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
86     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
87     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
88     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
89     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
90     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
91     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
92     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
93     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
94     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
95     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
96     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
97     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
98     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
99     [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
100    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
101    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
102    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
103    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
104    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
105    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
106    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
107    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
108    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
109    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
110    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
111    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
112    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
113    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
114    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
115    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
116    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
117    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
118    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
119    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
120    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
121    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
122    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
123    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
124    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
125    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
126    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
127    [ , ", -, a, b, c, d, e, f, g, h, i, j, k, l, ...
Name: letters, dtype: object

#Зроблено після основного часу виконання. Я помилилась і звернулась до AI за поясненням

In [ ]:
df["hash32"] = df['letters'].apply(
    lambda s: np.bitwise_or.reduce(
        np.left_shift(
            np.uint32(1),
            np.unique(np.frombuffer("".join(sorted(s)).encode("ascii"), dtype=np.uint8) - ord("a"))
        )
    ).astype(np.uint32)
)

In [ ]:
df["hash32"]

0      33488895
1      33488895
2      33488895
3      33488895
4      33488895
5      33488895
6      33488895
7      33488895
8      33488895
9      33488895
10     33488895
11     33488895
12     33488895
13     33488895
14     33488895
15     33488895
16     33488895
17     33488895
18     33488895
19     33488895
20     33488895
21     33488895
22     33488895
23     33488895
24     33488895
25     33488895
26     33488895
27     33488895
28     33488895
29     33488895
30     33488895
31     33488895
32     33488895
33     33488895
34     33488895
35     33488895
36     33488895
37     33488895
38     33488895
39     33488895
40     33488895
41     33488895
42     33488895
43     33488895
44     33488895
45     33488895
46     33488895
47     33488895
48     33488895
49     33488895
50     33488895
51     33488895
52     33488895
53     33488895
54     33488895
55     33488895
56     33488895
57     33488895
58     33488895
59     33488895
60     33488895
61     33488895
62     33488895
63     33488895
64     33488895
65     33488895
66     33488895
67     33488895
68     33488895
69     33488895
70     33488895
71     33488895
72     33488895
73     33488895
74     33488895
75     33488895
76     33488895
77     33488895
78     33488895
79     33488895
80     33488895
81     33488895
82     33488895
83     33488895
84     33488895
85     33488895
86     33488895
87     33488895
88     33488895
89     33488895
90     33488895
91     33488895
92     33488895
93     33488895
94     33488895
95     33488895
96     33488895
97     33488895
98     33488895
99     33488895
100    33488895
101    33488895
102    33488895
103    33488895
104    33488895
105    33488895
106    33488895
107    33488895
108    33488895
109    33488895
110    33488895
111    33488895
112    33488895
113    33488895
114    33488895
115    33488895
116    33488895
117    33488895
118    33488895
119    33488895
120    33488895
121    33488895
122    33488895
123    33488895
124    33488895
125    33488895
126    33488895
127    33488895
Name: hash32, dtype: uint32

In [ ]:
print(df[["City", "hash32"]].head(20))

                  City    hash32
0         "Youngstown"  33488895
1            "Yankton"  33488895
2             "Yakima"  33488895
3          "Worcester"  33488895
4    "Wisconsin Dells"  33488895
5      "Winston-Salem"  33488895
6           "Winnipeg"  33488895
7         "Winchester"  33488895
8         "Wilmington"  33488895
9         "Wilmington"  33488895
10         "Williston"  33488895
11      "Williamsport"  33488895
12        "Williamson"  33488895
13     "Wichita Falls"  33488895
14           "Wichita"  33488895
15          "Wheeling"  33488895
16   "West Palm Beach"  33488895
17         "Wenatchee"  33488895
18              "Weed"  33488895
19          "Waycross"  33488895